server:
  port: 8100
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver             # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/v_mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 30000
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 30000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      filters: stat,wall
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*, *.js, *.jpeg, *.jpg, *.png, *.gif, *.css
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 3000
          log-slow-sql: true
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为 500kb
      max-request-size: 512000  # 请求大小限制为 500kb
#  session:
#    store-type: redis

############################################################
#
# mybatis 配置
#
############################################################
mybatis-plus:
  type-aliases-package: com.vmall.entity    # 实体层
  mapper-locations: classpath:mapper/*.xml          # mapper 层
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
